### ISSUE TITLE
Explaining Random Forest on Pima Indians Diabetes Database

### ISSUE THREAD

**Issue by fangkuoyu** [biolab/orange3-explain#28]
Dear Support Team:

I am working on Pima Indians Diabetes Database from https://www.kaggle.com/uciml/pima-indians-diabetes-database.

Some questions on the attached diagrams:

1. Figure 1. Does the first row in the prediction widget showing "0.70 : 0.30 -> 0" means that the prediction is 0 and no diabetes under a threshold 0.5? Furthermore,  Does the explanation widget showing the higher value in Y axis towards prediction 0?
  
2. Figure 2. blue/red in the statistics widget and blue/red in the explanation widget seems different things. Does that "blue in the statistics widget means 0 while blue in the explanation widget supports 1"?

![2021-05-19_174645](https://user-images.githubusercontent.com/48971165/118793102-df0ce180-b8ca-11eb-9e98-a470cf764eca.png)

![2021-05-19_194320](https://user-images.githubusercontent.com/48971165/118807140-7d547380-b8da-11eb-973a-91a0f2bc61a6.png)

**Comment by ajdapretnar** [comment]
1. Yes for both statements.
2. Yes, blue and red in Feature Statistics is different from blue and red in Explain Prediction. Blue in statistics is the first class value in Domain (you can check the domain in Edit Domain or change the color with Color widget). From the documentation: "_Red features increase the probability for a selected class while blue features decrease the probability._"

**Comment by fangkuoyu** [comment]
Got it. Thanks for the comments.
