### ISSUE TITLE
Explain Model: buggy spin

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-explain#31]
I have noticed a buggy spin box in Explain Model. Posting it here as I haven't seen this elsewhere (to my knowledge). Perhaps an odd update call?

![bug](https://user-images.githubusercontent.com/12524972/122263783-1cb75700-ced7-11eb-87eb-d76fcfcb963b.gif)

**Comment by markotoplak** [comment]
These strange Macs and their spins... @borondics once reported a problem that his spin in k-means has a step of 2, but I could not replicate it. @borondics, did you ever seen anything like this? Thanks.

**Comment by ajdapretnar** [comment]
I cannot reproduce this anymore. I think it was fixed a while back (reference to Topic Modeling, which had the same issue). Cannot find the proper PR which fixed the issue.
