### ISSUE TITLE
Missing three of the four options...

### ISSUE THREAD

**Issue by Chocoder** [biolab/orange3-explain#45]
Hello! I installed the explain widget with conda option BUT I can only see one (the first) from the four options it should offer... is there any trick to get the four options in the list? Thanks

**Comment by ajdapretnar** [comment]
Please explain in more detail what is wrong, preferably providing a screenshot of the issue.

**Comment by Chocoder** [comment]
@jultou-raa I think you had this very issue? Could you provide some screen capture? Thanks,

**Comment by jultou-raa** [comment]
Hi @Chocoder and @ajdapretnar,

I have this issue indeed. I can provide a screenshot here, of course ! 

![Screenshot](https://user-images.githubusercontent.com/64092886/186664342-18147893-ae4a-49a8-8b95-9c1d3890f040.png)

And this is my installation :

|Package|Version|
|---:|:---:|
orange-canvas-core|            0.1.26
Orange-Spectroscopy|           0.6.5
orange-widget-base|            4.17.0
Orange3|                       3.32.0
Orange3-Educational|           0.5.0
Orange3-Explain|               0.5.3
Orange3-Timeseries|            0.3.10

And I got only 1 warning at startup :

```bash
C:\Users\XXXX\.conda\envs\orange3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
```

**Comment by jultou-raa** [comment]
Just saw there is a 0.6.0 update.

Downloading it, updating `orange-canvas-core` to version `0.1.27` and fixing a dependency issue (missing `pandas_datareader`) fixes the issue for me.

![image](https://user-images.githubusercontent.com/64092886/186667321-0d79cd14-1c2d-4816-a330-e2ab12ddf2d1.png)

**Comment by ajdapretnar** [comment]
My guess is that shap library wasn't properly installed before. Closing the issue since it seems to be resolved in the latest version.
