### ISSUE TITLE
How can I install Explain addon without upgrading core packages?

### ISSUE THREAD

**Issue by sohbl** [biolab/orange3-explain#56]
Hi, I'm using Orange version 3.32.0 now. I needed the **Explain** add-on (via Options > Add-ons) and it requires me to upgrade the core packages.

Is there any way I can install Explain addon without upgrading the core packages?

Thank you.

**Comment by PrimozGodec** [comment]
Hi, sorry for causing inconvenience. The newest version of explain addon needs at least Orange 3.33, and it cannot be avoided, but you can install an older version. Version 0.6.0 will do. 

On Windows:
- Open Orange Command Prompt (you can find it by searching on the start menu, or you can find the location where Orange is installed (right-click on Orange shortcut>Properties>Open location and the Orange command prompt is in the same directory)
- Run the command: `conda install orange3-explain=0.6.0 -c conda-forge`

On MacOS:
- Open Terminal (find it among applications)
- Run the command: `/Applications/Orange3.app/Contents/MacOS/pip install orange3-explain==0.6.0` if Orange is installed in Applications. If it is installed elsewhere, change it accordingly.

If you need any more help, please let us know.
